version: '3.8'

services:
  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /home/portico/static:/home/portico/static
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - portico-network
    restart: unless-stopped

networks:
  portico-network:
    external: true

volumes:
  caddy_data:
  caddy_config:
