name: Development Release

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  dev-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Get dev version
      id: version
      run: |
        VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
        VERSION=${VERSION#v}
        COMMIT=$(git rev-parse --short HEAD)
        DEV_VERSION="${VERSION}-dev-${COMMIT}"
        echo "version=$DEV_VERSION" >> $GITHUB_OUTPUT
        echo "tag=$DEV_VERSION" >> $GITHUB_OUTPUT
    
    - name: Build binaries
      run: |
        mkdir -p dist
        
        platforms=(
          "linux/amd64"
          "linux/arm64"
          "darwin/amd64"
          "darwin/arm64"
          "windows/amd64"
        )
        
        for platform in "${platforms[@]}"; do
          os=$(echo $platform | cut -d'/' -f1)
          arch=$(echo $platform | cut -d'/' -f2)
          
          echo "Building for $os/$arch..."
          
          if [ "$os" = "windows" ]; then
            ext=".exe"
          else
            ext=""
          fi
          
          GOOS=$os GOARCH=$arch go build \
            -ldflags "-X main.version=${{ steps.version.outputs.version }}" \
            -o "dist/portico-$os-$arch$ext" \
            ./cmd/portico
        done
    
    - name: Create checksums
      run: |
        cd dist
        sha256sum * > checksums.txt
    
    - name: Create Development Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.version.outputs.tag }}
        name: Portico Development ${{ steps.version.outputs.tag }}
        prerelease: true
        files: |
          dist/*
        body: |
          ## Portico Development Build ${{ steps.version.outputs.tag }}
          
          This is a development build from the `develop` branch.
          
          ### Installation
          
          **Linux/macOS:**
          ```bash
          curl -fsSL https://raw.githubusercontent.com/portico/portico/main/install.sh | bash
          ```
          
          ### What's New
          - 🚧 Development features
          - 🐛 Bug fixes
          - 🧪 Experimental functionality
          
          ### Files
          - `portico-linux-amd64` - Linux x86_64
          - `portico-linux-arm64` - Linux ARM64
          - `portico-darwin-amd64` - macOS x86_64
          - `portico-darwin-arm64` - macOS ARM64 (Apple Silicon)
          - `portico-windows-amd64.exe` - Windows x86_64
          - `checksums.txt` - SHA256 checksums
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
